apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Target namespace for all resources
namespace: 3tirewebapp-dev

# Resources to include
resources:
  - namespace.yaml
  - postgres-complete.yaml
  - backend-complete.yaml
  - frontend-complete.yaml
  - external-secrets-placeholder.yaml

# Common annotations (safe to apply to all resources)
commonAnnotations:
  app.kubernetes.io/version: "1.0"
  managed-by: "kustomize"

# Centralized image management
images:
  - name: itsbaivab/frontend
    newTag: v2
  - name: itsbaivab/backend
    newTag: latest
  - name: postgres
    newTag: "15"

# Resource scaling
replicas:
  - name: frontend
    count: 2
  - name: backend
    count: 2
  - name: postgres
    count: 1
