apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: goal-tracker

resources:
  - ../../base

patchesStrategicMerge:
  - replica-patch.yaml

commonLabels:
  environment: dev

images:
  - name: itsbaivab/backend
    newTag: latest
  - name: itsbaivab/frontend
    newTag: latest
